server:
  port: 9001
  servlet:
    context-path: /services

security:
  oauth2:
    client:
      client-id: panel-service
      client-secret: panel-service-secret
    resource:
      user-info-uri: http://localhost:9000/services/user
