instance:
  id: 1

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

server:
  port: 0 # Bind to a random available port on startup.

security:
  oauth2:
    client:
      client-id: panel-service
      client-secret: panel-service-secret
    resource:
      user-info-uri: http://localhost:9000/services/user

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    # The ID of this particular instance of the service.
    instance-id: ${spring.application.name}:${instance.id}

management:
  endpoints:
    web:
      exposure:
        include: "*"