spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

server:
  port: 0 # Bind to a random available port on startup.
  servlet:
    context-path: /services

security:
  oauth2:
    client:
      client-id: panel-service
      client-secret: panel-service-secret
    resource:
      user-info-uri: http://localhost:9000/services/user
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    # The ID of this particular instance of the service.
    # In reality, this would be some logical name configured as part of the environment.
    # In development, we just generate a random number to allow multiple instances to be run concurrently.
    instance-id: ${spring.application.name}:${random.int}
